// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use diesel::Queryable;
use diesel::Identifiable;
use diesel::prelude::Associations;
use diesel::prelude::Insertable;
use crate::schema::{users, sessions};



#[derive(Queryable, Debug, Identifiable, Insertable)]
#[diesel(primary_key(user_id))]
pub struct User {
    pub user_id: i32,
    pub username: String,
    pub acc_password: String,
    pub first_name: String,
    pub last_name: String,
    pub creation_date: Option<chrono::NaiveDate>,
}

#[derive(Queryable, Debug, Identifiable, Insertable, Associations)]
#[diesel(primary_key(user_id, session_id))]
#[diesel(belongs_to(User))]
pub struct Session {
    pub user_id: i32,
    pub session_id : String
}